Repository atlp-rwanda/alpha-ec-be, pull requests merged in 2024-04, with the labels that each got.

#24 feat(Product CRUD): CRUD operation of product
  .gitignore
  package-lock.json
  package.json
  src/app.ts
  src/config/config.js
  src/config/passportConfig.ts
  src/controllers/index.ts
  src/controllers/productController.ts
  src/database/migrations/20240203095501-create-role.js
  src/database/migrations/20240404084003-create-product.js
  src/database/models/index.ts
  src/database/models/product.ts
  src/database/models/user.ts
  src/database/seeders/20240325175816-demo-user.js
  src/helper/excOperation.ts
  src/helper/index.ts
  src/helper/productQueries.ts
  src/middleware/authentication.ts
  src/middleware/fileUpload.ts
  src/middleware/index.ts
  src/middleware/validate.ts
  src/routers/index.ts
  src/routers/productRoute.ts
  src/swagger.json
  src/utils/cloud.ts
  src/utils/index.ts
  src/utils/pagination.ts
  src/utils/response.ts
  src/validations/index.ts
  src/validations/productValidation.ts
  test/assets/typescript.jpeg
  test/product.test.ts
Labels: Ready for review

#29 feat(login-via-google):user can login via google
  package-lock.json
  package.json
  src/app.ts
  src/config/passport-setup.ts
  src/controllers/authController.ts
  src/database/migrations/20240411085039-add_auth_columns_to_users.js
  src/database/models/user.ts
  src/database/seeders/20240204142906-insert-roles.js
  src/middleware/authentication.ts
  src/routers/authRoute.ts
  src/routers/index.ts
  src/swagger.json
  src/utils/cloud.ts
  src/utils/pagination.ts
  src/utils/tokenGenerate.ts
  test/auth.test.ts
  test/product.test.ts
Labels: Ready for review

#26 feat(update-user-password):user updating password
  .env.example
  package.json
  src/config/config.js
  src/config/passportConfig.ts
  src/controllers/changePasswordController.ts
  src/controllers/loginController.ts
  src/database/seeders/20240325175816-demo-user.js
  src/helper/local.strategy.ts
  src/middleware/loginMiddleware.ts
  src/routers/userRoute.ts
  src/swagger.json
  src/utils/tokenGenerate.ts
  src/validations/newPasswordValidation.ts
  test/auth.test.ts
  test/login.test.ts
  test/product.test.ts
  test/updatePassword.test.ts
Labels: enhancement, Ready for review

#25 Ft update profile 187300152
  .gitignore
  README.md
  package-lock.json
  package.json
  src/config/config.js
  src/config/passport-setup.ts
  src/controllers/update-profileController.ts
  src/controllers/userController.ts
  src/database/migrations/20240325172706-update-profile.js
  src/database/models/user.ts
  src/database/seeders/20240325175816-demo-user.js
  src/middleware/authentication.ts
  src/middleware/fileUpload.ts
  src/middleware/validate.ts
  src/routers/userRoute.ts
  src/swagger.json
  src/utils/cloud.ts
  src/utils/pagination.ts
  src/validations/userValidation.ts
  test/product.test.ts
  test/profile-updatetest.ts
  test/user.test.ts
Labels: Ready for review

#30 #187300141 User email verification
  README.md
  package-lock.json
  package.json
  src/controllers/loginController.ts
  src/controllers/userController.ts
  src/controllers/userVerifyController.ts
  src/database/models/user.ts
  src/database/seeders/20240411132319-add-user.js
  src/routers/userRoute.ts
  src/swagger.json
  src/utils/email.ts
  src/utils/index.ts
  src/utils/jwtToken.ts
  src/utils/views/email.handlebars
  test/login.test.ts
  test/product.test.ts
  test/profile-updatetest.ts
  test/role.test.ts
  test/updatePassword.test.ts
  test/user.test.ts
  test/userVerify.test.ts
Labels: enhancement, Ready for review

#31 #187300145 User Logout
  package-lock.json
  package.json
  src/controllers/index.ts
  src/controllers/logoutController.ts
  src/controllers/productController.ts
  src/database/migrations/20240404162044-create-logout.js
  src/database/models/index.ts
  src/database/models/logout.ts
  src/database/seeders/20240325175816-demo-user.js
  src/database/seeders/20240404165310-logout-seed.js
  src/database/seeders/20240411132319-add-user.js
  src/middleware/authentication.ts
  src/routers/userRoute.ts
  src/swagger.json
  test/logout.test.ts
Labels: Ready for review

#35 fix(Product CRUD): CRUD operation of product
  src/controllers/categoryController.ts
  src/controllers/changePasswordController.ts
  src/controllers/productController.ts
  src/database/migrations/20240404084001-create-category.js
  src/database/migrations/20240404084003-create-product.js
  src/database/models/category.ts
  src/database/models/index.ts
  src/database/models/product.ts
  src/database/seeders/20240325175816-demo-user.js
  src/database/seeders/20240414205853-create-category.js
  src/helper/excOperation.ts
  src/helper/productQueries.ts
  src/routers/categoryRoute.ts
  src/routers/index.ts
  src/swagger.json
  src/utils/validations.ts
  src/validations/categoryValidation.ts
  src/validations/productValidation.ts
  test/category.test.ts
  test/product.test.ts
  test/role.test.ts
Labels: Ready for review

#38 fix-login-via-google
  package.json
  src/config/passport-setup.ts
  src/controllers/authController.ts
  src/utils/email.ts
  src/utils/tokenGenerate.ts
  test/auth.test.ts
Labels: Ready for review

#44 feat(setup docker): Setup docker for backend
  .Dockerignore
  .gitignore
  Docker-compose.yml
  Dockerfile
  entrypoint.sh
  package-lock.json
  package.json
  src/controllers/changePasswordController.ts
  src/controllers/userController.ts
  src/middleware/loginMiddleware.ts
Labels: Ready for review

#43 #187300153 Admin Account Disable and Activate
  package-lock.json
  src/config/config.js
  src/controllers/loginController.ts
  src/controllers/userController.ts
  src/controllers/userStatusController.ts
  src/database/migrations/20240422091002-add-status.js
  src/database/models/user.ts
  src/database/seeders/20240411132319-add-user.js
  src/database/seeders/20240419193057-add-status.js
  src/routers/userRoute.ts
  src/swagger.json
  src/utils/views/activateAccount.handlebars
  src/utils/views/suspendAccount.handlebars
  src/utils/views/verifyAccount.handlebars
  test/login.test.ts
  test/userStatus.test.ts
Labels: enhancement, Ready for review

#48 Ft chat application 187300175
  package-lock.json
  package.json
  public/index.html
  src/app.ts
  src/chatSetup.ts
  src/controllers/chatController.ts
  src/database/migrations/20240421113110-create-chat.js
  src/database/models/chat.ts
  src/database/models/index.ts
  src/database/models/user.ts
  src/routers/userRoute.ts
  src/server.ts
  src/swagger.json
  src/utils/tokenGenerate.ts
  test/bchat.test.ts
  test/login.test.ts
  tsconfig.json
Labels: enhancement

#49 fix(chat):i was fixing chat 187300175
  public/index.html
  src/config/config.js
  test/bchat.test.ts
Labels: bug

#47 #187432706 A seller avail/unavail a product
  public/index.html
  src/controllers/logoutController.ts
  src/controllers/productController.ts
  src/controllers/userController.ts
  src/database/models/index.ts
  src/database/models/product.ts
  src/database/models/user.ts
  src/database/seeders/20240411132319-add-user.js
  src/helper/productQueries.ts
  src/middleware/authentication.ts
  src/middleware/statuscheck.ts
  src/routers/productRoute.ts
  src/routers/userRoute.ts
  src/swagger.json
  src/utils/jwtToken.ts
  src/validations/productValidation.ts
  test/logout.test.ts
  test/product.test.ts
  test/resetPassword.test.ts
  test/role.test.ts
Labels: Ready for review

#41 Ft cart 187300163
  package-lock.json
  package.json
  src/controllers/cartsController.ts
  src/controllers/update-profileController.ts
  src/database/migrations/20240418124925-create-cart.js
  src/database/models/cart.ts
  src/database/models/index.ts
  src/database/models/product.ts
  src/database/models/user.ts
  src/routers/cartRoutes.ts
  src/routers/index.ts
  src/swagger.json
  src/utils/cartsCalculations.ts
  src/utils/index.ts
  src/validations/cartvalidation.ts
  src/validations/index.ts
  test/product.test.ts
  test/profile.update.test.ts
  test/rf.carttest.ts
  test/wishlist.test.ts
  tsconfig.json
Labels: Ready for review

#50 feat(product-review):A buyer can provide a review on a product
  .DS_Store
  package.json
  src/controllers/categoryController.ts
  src/controllers/productController.ts
  src/controllers/replyController.ts
  src/controllers/reviewController.ts
  src/database/migrations/20240424134441-review-migration.js
  src/database/migrations/20240424163529-replies.js
  src/database/migrations/20240425094156-update-product-table.js
  src/database/models/index.ts
  src/database/models/product.ts
  src/database/models/reply.ts
  src/database/models/review.ts
  src/database/models/user.ts
  src/routers/index.ts
  src/routers/reviewRoute.ts
  src/swagger.json
  src/utils/pagination.ts
  src/validations/reviewValidation.ts
  test/category.test.ts
  test/product.test.ts
  test/review.test.ts
Labels: Ready for review

#45 Ft stop listing expired products 187300172
  .env.example
  package-lock.json
  package.json
  src/database/migrations/20240404084003-create-product.js
  src/database/models/product.ts
  src/expiryCronJob.ts
  src/server.ts
  src/utils/productExpiryNotifier.ts
  src/utils/views/expiryNotification.handlebars
  test/productExpiry.test.ts
  test/rf.carttest.ts
Labels: Ready for review
